# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/clusters_ejemplo',
                'doc_host': 'https://AzulEren.github.io',
                'git_url': 'https://github.com/AzulEren/clusters_ejemplo',
                'lib_path': 'clusters_ejemplo'},
  'syms': {'clusters_ejemplo.core': {'clusters_ejemplo.core.foo': ('core.html#foo', 'clusters_ejemplo/core.py')}}}
